name: Build Flutter iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for iOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          architecture: x64

      - name: Clean build artifacts
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Pre-cache iOS simulator build
        run: flutter precache --ios --universal

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --repo-update

          
      - name: Build iOS for simulator
        run: flutter build ios --simulator




